version: '3'

services:
  api:
    build: ./
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
  api_migrate:
    extends:
      service: api
    command: python manage.py migrate
  api_run:
    extends:
      service: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'